version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}

version: "3.9"

services :

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # CONTAINER - PHPMYADMIN : https://hub.docker.com/r/phpmyadmin/phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - wp

  #nginx

  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8000:80"

  
  # composer:
  #   image: composer:2.1.8
  #   container_name: "composer_container"
  #   volumes:
  #     - .:/app
  #     # - ./.docker/nginx/default.conf
  #   # command: bash -c "composer install && composer update"


  composer:
    image: composer:2.1.8
    container_name: "composer_container"
    command: ["composer", "install"]
    volumes:
      - ./:/app

networks:
  wp:

volumes:
  db_data: